### ISSUE TITLE
[Bug]: WAU autoupdate disabled.

### ISSUE THREAD

**Issue by mtylich** [Weatherlights/Winget-AutoUpdate-Intune#31]
### The problem

We used your package from MS store and why it's by default updates for WAU turned off?  We did not changed anything 

### What version of WAU has the issue?

1.17.8

### What version of Windows are you using (ex. Windows 11 22H2)?

22H2

### What version of winget are you using?

1.7.10661

**Comment by xdaass** [comment]
thank you for the hard work , basically it works OK , 
Same here, it seems that this doesnt got updated , what are the plans to fix this? 
there are bugs on relaying on the exclud appl list, where some apps got updated regardless of being stated in the black list, 
im looking to evaluate if its due to the old version of WAU, nut it set not to be updated when looking on the lastcommand initiated 
-silent -DoNotUpdate -DisableWAUAutoUpdate -NoClean -NotificationLevel Full -ModsPath "C:\ProgramData\Winget-AutoUpdate-Configurator\mods" -UpdatesInterval Daily -BypassListForUsers -UpdatesAtLogon -StartMenuShortcut -InstallUserContext -ListPath "C:\ProgramData\Winget-AutoUpdate-Configurator\"

**Comment by Weatherlights** [comment]
Updates are provided by the Microsoft Store or manually through a new MSI package. One aspect of this project is code integrity and therefore all powershell/binary code is signed.
