### ISSUE TITLE
[Feature Request]: Consider log location

### ISSUE THREAD

**Issue by MarcoBuess** [Weatherlights/Winget-AutoUpdate-Intune#40]
### The request

It would be nice if you'd consider putting the log files to the IMEs (Intune Management Extension) log location if applicable (like Romanitho suggests). Problem is, that `C:\Windows\Temp` can not be accessed easily remotely on Entra joined devices. Therefore if a user doesn't have local admin permission (which most shouldn't) there is no way you can get access to the logs. You can collect them remotely through Intune, which will collect everything under `C:\ProgramData\Microsoft\IntuneManagementExtension\Logs`.

**Comment by Weatherlights** [comment]
Will reconsider it... My design decision was not to tamper in folders that do not belong to other applications. The Logfiles under c:\Windows\temp can also be collected through the Collect Logs feature (I made sure to select a folder and naming pattern that is on the list of folders that is supported for collection of logs).
But I can fully understand and will rethink it since most other applications also decided to use the IME folder aswell.

**Comment by Weatherlights** [comment]
Give me a moment :)... I just want to rethink this in all directions... maybe adding an additional log location as a parameter to the ADMX/ADML.

**Comment by MarcoBuess** [comment]
Would make sense. Also log location seems to be kinda hard coded in these locations:
1. https://github.com/Weatherlights/Winget-AutoUpdate-Intune/blob/117479f7a6e7078b1d4a5b1e67a4a7090ef4447a/Refresh-WingetConfiguration.ps1#L320
2. https://github.com/Weatherlights/Winget-AutoUpdate-Intune/blob/ed0fcd136b271f190b4f5a2fe6a7c5bf621e77ed/WinGet-AutoUpdate-Configurator/Generic.psm1#L28
